spring:
  application:
    name: DailySnapshot-Backend

server:
  address: 192.168.1.157
  port: 8080

external:
  open-meteo:
    baseUrl: https://api.open-meteo.com/v1
    geocodingBaseUrl: https://geocoding-api.open-meteo.com/v1
  frankfurter:
    baseUrl: https://api.frankfurter.dev/v1
  news:
    baseUrl: https://news.google.com/rss/search
